Uncomment test and release

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,49 +7,47 @@ on:
   push:
     branches:
       - master
-  pull_request:
+  pull_request: # TODO remove after test
 jobs:
   build:
     runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v2
-#      - name: Preload last stable image as a cache
-#        run: 'docker pull sharifwss/web:latest || echo "Unable to pull cache. exit code: $?"'
+      - name: Preload last stable image as a cache
+        run: 'docker pull sharifwss/web:latest || echo "Unable to pull cache. exit code: $?"'
       - run: echo "WEB_IMAGE_VERSION=snapshot-$GITHUB_RUN_ID" >> $GITHUB_ENV
       - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKER_USERNAME --password-stdin
       - run: docker-compose build
       - run: docker-compose push web
-  #  test:
-  #    needs: build
-  #    runs-on: ubuntu-20.04
-  #    steps:
-  #      - uses: actions/checkout@v2
-  #      - run: echo "VERSION=snapshot-$GITHUB_RUN_ID" >> $GITHUB_ENV
-  #      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKER_USERNAME --password-stdin
-  #      - run: docker-compose pull
-  #      - run: docker-compose up -d --no-build
-  #      - name: Wait for the app to be up
-  #        run: sleep 20
-  #      - name: Smoke test
-  #        run: ./.github/scripts/smoke-test.sh "http://localhost"
-#    release:
-#      needs:
-#        - build
-#        - test
-#      runs-on: ubuntu-20.04
-#      steps:
-#        - run: echo "SNAPSHOT_VERSION=snapshot-$GITHUB_RUN_ID" >> $GITHUB_ENV
-#        - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKER_USERNAME --password-stdin
-#        - run: docker pull sharifwss/web:$SNAPSHOT_VERSION
-#        - run: docker tag sharifwss/web:$SNAPSHOT_VERSION sharifwss/web:$RELEASE_VERSION
-#        - run: docker tag sharifwss/web:$SNAPSHOT_VERSION sharifwss/web:latest
-#        - run: docker push sharifwss/web:$RELEASE_VERSION
-#        - run: docker push sharifwss/web:latest
+    test:
+      needs: build
+      runs-on: ubuntu-20.04
+      steps:
+        - uses: actions/checkout@v2
+        - run: echo "VERSION=snapshot-$GITHUB_RUN_ID" >> $GITHUB_ENV
+        - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKER_USERNAME --password-stdin
+        - run: docker-compose pull
+        - run: docker-compose up -d --no-build
+        - name: Wait for the app to be up
+          run: sleep 20
+        - name: Smoke test
+          run: ./.github/scripts/smoke-test.sh "http://localhost"
+    release:
+      needs:
+        - build
+        - test
+      runs-on: ubuntu-20.04
+      steps:
+        - run: echo "SNAPSHOT_VERSION=snapshot-$GITHUB_RUN_ID" >> $GITHUB_ENV
+        - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKER_USERNAME --password-stdin
+        - run: docker pull sharifwss/web:$SNAPSHOT_VERSION
+        - run: docker tag sharifwss/web:$SNAPSHOT_VERSION sharifwss/web:$RELEASE_VERSION
+        - run: docker tag sharifwss/web:$SNAPSHOT_VERSION sharifwss/web:latest
+        - run: docker push sharifwss/web:$RELEASE_VERSION
+        - run: docker push sharifwss/web:latest
   test-deploy:
     needs:
       - build
-    #      - test
-    #      - release
     runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v2
